export enum RoleEnum {
  ADMIN = 'admin',
  MODERATOR = 'moderator',
  HELPER = 'helper',
  POLICE = 'police',
  USER = 'user',
}

export enum VipEnum {
  IRON = 'iron',
  GOLD = 'gold',
  DIAMOND = 'diamond',
  NETHERITE = 'netherite',
}

export enum CategoryEnum {
  BUILD_BLOCKS = 'build_blocks',
  COLOR_BLOCKS = 'color_blocks',
  FOODS_AND_POTIONS = 'foods_and_potions',
  FUNCTIONAL_BLOCKS = 'functional_blocks',
  NATURE_BLOCKS = 'nature_blocks',
  INGREDIENTS = 'ingredients',
  REDSTONE_BLOCKS = 'redstone_blocks',
  TOOLS = 'tools',
  WEAPONS = 'weapons',
  SHULKERS = 'shulkers',
  ENCHANTED_BOOK = 'enchanted_book',
}

export enum WorldEnum {
  WORLD = 'world',
  WORLD_NETHER = 'world_nether',
  WORLD_END = 'world_end',
}

export enum EnchantsTypesEnum {
  HELMET = 'helmet',
  CHESTPLATE = 'chestplate',
  LEGGINGS = 'leggings',
  BOOTS = 'boots',
  ELYTRA = 'elytra',
  SWORD = 'sword',
  AXE = 'axe',
  TRIDENT = 'trident',
  MACE = 'mace',
  PICKAXE = 'pickaxe',
  SHOVEL = 'shovel',
  HOE = 'hoe',
  BOW = 'bow',
  CROSSBOW = 'crossbow',
  FISHING_ROD = 'fishing_rod',
}

export enum EnchantsEnum {
  BANE_OF_ARTHROPODS = 'bane_of_arthropods',
  BLAST_PROTECTION = 'blast_protection',
  BREACH = 'breach',
  DENSITY = 'density',
  DEPTH_STRIDER = 'depth_strider',
  EFFICIENCY = 'efficiency',
  FEATHER_FALLING = 'feather_falling',
  FIRE_ASPECT = 'fire_aspect',
  FIRE_PROTECTION = 'fire_protection',
  FORTUNE = 'fortune',
  FROST_WALKER = 'frost_walker',
  IMPALING = 'impaling',
  KNOCKBACK = 'knockback',
  LOOTING = 'looting',
  LOYALTY = 'loyalty',
  LUCK_OF_THE_SEA = 'luck_of_the_sea',
  LURE = 'lure',
  PIERCING = 'piercing',
  POWER = 'power',
  PROJECTILE_PROTECTION = 'projectile_protection',
  PROTECTION = 'protection',
  PUNCH = 'punch',
  QUICK_CHARGE = 'quick_charge',
  RESPIRATION = 'respiration',
  RIPTIDE = 'riptide',
  SHARPNESS = 'sharpness',
  SMITE = 'smite',
  SOUL_SPEED = 'soul_speed',
  SWEEPING_EDGE = 'sweeping_edge',
  SWIFT_SNEAK = 'swift_sneak',
  THORNS = 'thorns',
  UNBREAKING = 'unbreaking',
  WIND_BURST = 'wind_burst',
  AQUA_AFFINITY = 'aqua_affinity',
  BINDING_CURSE = 'binding_curse',
  CHANNELING = 'channeling',
  VANISHING_CURSE = 'vanishing_curse',
  SILK_TOUCH = 'silk_touch',
  MENDING = 'mending',
  MULTISHOT = 'multishot',
  INFINITY = 'infinity',
  FLAME = 'flame',
}
