export enum RoleEnum {
  ADMIN = 'admin',
  MODERATOR = 'moderator',
  HELPER = 'helper',
  POLICE = 'police',
  USER = 'user',
}

export enum CategoryEnum {
  BUILD_BLOCKS = 'build_blocks',
  COLOR_BLOCKS = 'color_blocks',
  FOODS_AND_POTIONS = 'foods_and_potions',
  FUNCTIONAL_BLOCKS = 'functional_blocks',
  NATURE_BLOCKS = 'nature_blocks',
  INGREDIENTS = 'ingredients',
  REDSTONE_BLOCKS = 'redstone_blocks',
  TOOLS = 'tools',
  WEAPONS = 'weapons',
  SHULKERS = 'shulkers',
  ENCHANTED_BOOK = 'enchanted_book',
}

export enum EnchantsWithoutLvl {
  AQUA_AFFINITY = 'aqua_affinity',
  BINDING_CURSE = 'binding_curse',
  CHANNELING = 'channeling',
  VANISHING_CURSE = 'vanishing_curse',
  SILK_TOUCH = 'silk_touch',
  MENDING = 'mending',
  MULTISHOT = 'multishot',
  INFINITY = 'infinity',
  FLAME = 'flame',
}

export const enchantsWithMaxLvl = {
  bane_of_arthropods: 5,
  blast_protection: 4,
  breach: 4,
  density: 5,
  depth_strider: 3,
  efficiency: 5,
  feather_falling: 4,
  fire_aspect: 2,
  fire_protection: 4,
  fortune: 3,
  frost_walker: 2,
  impaling: 5,
  knockback: 2,
  looting: 3,
  loyalty: 3,
  luck_of_the_sea: 3,
  lure: 3,
  piercing: 4,
  power: 5,
  projectile_protection: 4,
  protection: 4,
  punch: 2,
  quick_charge: 3,
  respiration: 3,
  riptide: 3,
  sharpness: 5,
  smite: 5,
  soul_speed: 3,
  sweeping: 3,
  sweeping_edge: 3,
  swift_sneak: 3,
  thorns: 3,
  unbreaking: 3,
  wind_burst: 3,
}

export enum EnchantsTypesEnum {
  HELMET,
  CHESTPLATE,
  LEGGINGS,
  BOOTS,
  SWORD,
  AXE,
  TRIDENT,
  PICKAXE_SHOVEL_HOE,
  BOW,
  CROSSBOW,
  FISHING_ROD,
  SHEARS,
  MENDING_UNBREAKING,
}

// export const enchantsWithTypes = {
//   bane_of_arthropods: 5,
//   blast_protection: 4,
//   breach: 4,
//   density: 5,
//   depth_strider: 3,
//   efficiency: 5,
//   feather_falling: 4,
//   fire_aspect: 2,
//   fire_protection: 4,
//   fortune: 3,
//   frost_walker: 2,
//   impaling: 5,
//   knockback: 2,
//   looting: 3,
//   loyalty: 3,
//   luck_of_the_sea: 3,
//   lure: 3,
//   piercing: 4,
//   power: 5,
//   projectile_protection: 4,
//   protection: 4,
//   punch: 2,
//   quick_charge: 3,
//   respiration: 3,
//   riptide: 3,
//   sharpness: 5,
//   smite: 5,
//   soul_speed: 3,
//   sweeping: 3,
//   sweeping_edge: 3,
//   swift_sneak: 3,
//   thorns: 3,
//   unbreaking: 3,
//   wind_burst: 3,
// }
